server:
  port: ${SERVER_PORT:8092}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:plazoleta_foodcourt_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:toor}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET}
  user: ${JWT_USER:AUTH0JWT_BACKEND}
  expiration: ${JWT_EXPIRATION:86400000}
  
  # Uncomment the following lines to enable debug logging

logging:
 level:
   root: debug